version: 1
update_configs:
- package_manager: "python"
  directory: "/{{cookiecutter.project_slug}}"
  update_schedule: "daily"
  default_reviewers:
  - "griceturrble"
  default_assignees:
  - "griceturrble"
